
# Welcome to The Graveyard Config!
#
# Structures:
# Configure separation (Minimum distance between two structures of this type in chunks. Must be less than spacing).
# Configure spacing (Average distance between two structure placement attempts of this type in chunks).
# Configure whitelist: use "#biomeCategory" for biome categories and "minecraft:biome" for biomes (mod identifier + ":" + biome name).
# Configure blacklist: use "#biomeCategory" for biome categories and "minecraft:biome" for biomes (mod identifier + ":" + biome name).
# Configure mod whitelist: use "#modid" to whitelist the biomes of the specified mod for structures to spawn in (examples: #minecraft, #graveyard, #graveyard_biomes, #terralith, #byg, #bop).
# Valid vanilla biome categories are: #taiga, #extreme_hills, #jungle, #mesa, #plains, #savanna, #icy, #beach, #forest, #desert, #swamp, #mushroom, #underground, #mountain.
# A full list of all the biomes can be found here https:minecraft.fandom.com/wiki/Biome#Biome_IDs.
#
# Mobs:
# Configure spawning weight and group size of the spawn.
# Configure if mobs burn in sunlight and/or if mobs are affected by the wither effect.
# Configure whitelist: use "#biomeCategory" for biome categories and "minecraft:biome" for biomes (mod identifier + ":" + biome name).
# Configure blacklist: use "#biomeCategory" for biome categories and "minecraft:biome" for biomes (mod identifier + ":" + biome name).
# Configure mod whitelist: use "#modid" to whitelist the biomes of the specified mod for structures to spawn in (examples: #minecraft, #graveyard, #graveyard_biomes, #terralith, #byg, #bop).
#
# Additional:
# Configure graveyard fog particles rising from moss and set the chance of spawning them (higher numbers = lower chance of spawning).
# Configure if hordes of graveyard mobs can spawn and set their size and frequency.
# Configure if urns have a double chest inventory.
#
["The Graveyard - Structures Config"]

	["The Graveyard - Structures Config".small_graveyard]
		generate = true
		#Range: 0 ~ 200
		spacing = 20
		#Range: 0 ~ 200
		separation = 18
		whitelist = ["#plains"]
		blacklist = []
		modWhitelist = ["#minecraft"]
		canSpawnGraveyardMobs = false

	["The Graveyard - Structures Config".small_desert_graveyard]
		generate = true
		#Range: 0 ~ 200
		spacing = 32
		#Range: 0 ~ 200
		separation = 28
		whitelist = ["#desert"]
		blacklist = []
		modWhitelist = ["#minecraft"]
		canSpawnGraveyardMobs = false

	["The Graveyard - Structures Config".small_grave]
		generate = true
		#Range: 0 ~ 200
		spacing = 12
		#Range: 0 ~ 200
		separation = 8
		whitelist = ["#taiga", "#forest", "#plains"]
		blacklist = []
		modWhitelist = ["#minecraft", "#graveyard_biomes"]
		canSpawnGraveyardMobs = false

	["The Graveyard - Structures Config".small_desert_grave]
		generate = true
		#Range: 0 ~ 200
		spacing = 20
		#Range: 0 ~ 200
		separation = 16
		whitelist = ["#desert"]
		blacklist = []
		modWhitelist = ["#minecraft"]
		canSpawnGraveyardMobs = false

	["The Graveyard - Structures Config".small_savanna_grave]
		generate = true
		#Range: 0 ~ 200
		spacing = 12
		#Range: 0 ~ 200
		separation = 8
		whitelist = ["#mesa", "#savanna"]
		blacklist = []
		modWhitelist = ["#minecraft"]
		canSpawnGraveyardMobs = false

	["The Graveyard - Structures Config".small_mountain_grave]
		generate = true
		#Range: 0 ~ 200
		spacing = 12
		#Range: 0 ~ 200
		separation = 8
		whitelist = ["#mountain", "#extreme_hills"]
		blacklist = []
		modWhitelist = ["#minecraft"]
		canSpawnGraveyardMobs = false

	["The Graveyard - Structures Config".mushroom_grave]
		generate = true
		#Range: 0 ~ 200
		spacing = 24
		#Range: 0 ~ 200
		separation = 18
		whitelist = ["#mushroom", "#jungle", "#swamp"]
		blacklist = []
		modWhitelist = ["#minecraft"]
		canSpawnGraveyardMobs = false

	["The Graveyard - Structures Config".memorial_tree]
		generate = true
		#Range: 0 ~ 200
		spacing = 14
		#Range: 0 ~ 200
		separation = 12
		whitelist = ["#forest"]
		blacklist = ["minecraft:forest", "minecraft:flower_forest", "minecraft:dark_forest", "minecraft:windswept_forest"]
		modWhitelist = ["#minecraft"]
		canSpawnGraveyardMobs = false

	["The Graveyard - Structures Config".medium_graveyard]
		generate = true
		#Range: 0 ~ 200
		spacing = 18
		#Range: 0 ~ 200
		separation = 16
		whitelist = ["#forest"]
		blacklist = ["minecraft:dark_forest", "minecraft:birch_forest", "minecraft:old_growth_birch_forest", "graveyard_biomes:haunted_lakes", "graveyard_biomes:haunted_forest"]
		modWhitelist = ["#minecraft", "#graveyard_biomes"]
		canSpawnGraveyardMobs = true

	["The Graveyard - Structures Config".large_graveyard]
		generate = true
		#Range: 0 ~ 200
		spacing = 12
		#Range: 0 ~ 200
		separation = 10
		whitelist = ["#forest", "#taiga"]
		blacklist = ["minecraft:forest", "minecraft:flower_forest", "minecraft:birch_forest", "minecraft:old_growth_birch_forest", "minecraft:windswept_forest", "graveyard_biomes:eroded_haunted_forest", "graveyard_biomes:haunted_lakes"]
		modWhitelist = ["#minecraft", "#graveyard_biomes"]
		canSpawnGraveyardMobs = true

	["The Graveyard - Structures Config".haunted_house]
		generate = true
		#Range: 0 ~ 200
		spacing = 25
		#Range: 0 ~ 200
		separation = 20
		whitelist = ["#forest", "#swamp"]
		blacklist = ["minecraft:forest", "minecraft:flower_forest", "minecraft:birch_forest", "minecraft:old_growth_birch_forest", "minecraft:windswept_forest", "graveyard_biomes:haunted_forest"]
		modWhitelist = ["#minecraft", "#graveyard_biomes"]
		canSpawnGraveyardMobs = false

["The Graveyard - Mob Spawning Config"]

	["The Graveyard - Mob Spawning Config".ghoul]
		enabled = true
		#Range: 0 ~ 100
		weight = 25
		#Range: 1 ~ 100
		minGroupSizeGhoul = 2
		#Range: 1 ~ 100
		maxGroupSizeGhoul = 5
		canBurnInSunlight = true
		canBeWithered = false
		whitelist = ["#jungle", "#extreme_hills", "#underground", "#mesa", "#mountain", "#icy", "#savanna", "#beach", "#plains", "#swamp", "#forest", "#taiga", "#desert"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes"]

	["The Graveyard - Mob Spawning Config".revenant]
		enabled = true
		#Range: 0 ~ 100
		weight = 25
		#Range: 1 ~ 100
		minGroupSizeRevenant = 5
		#Range: 1 ~ 100
		maxGroupSizeRevenant = 8
		canBurnInSunlight = true
		canBeWithered = false
		whitelist = ["#jungle", "#extreme_hills", "#underground", "#mesa", "#mountain", "#icy", "#savanna", "#beach", "#plains", "#swamp", "#forest", "#taiga", "#desert"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes"]

	["The Graveyard - Mob Spawning Config".reaper]
		enabled = true
		#Range: 0 ~ 100
		weight = 10
		#Range: 1 ~ 100
		minGroupSizeReaper = 2
		#Range: 1 ~ 100
		maxGroupSizeGhoul = 3
		canBurnInSunlight = true
		canBeWithered = false
		whitelist = ["graveyard_biomes:eroded_haunted_forest"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes"]

	["The Graveyard - Mob Spawning Config".nightmare]
		enabled = true
		#Range: 0 ~ 100
		weight = 7
		#Range: 1 ~ 100
		minGroupSizeNightmare = 1
		#Range: 1 ~ 100
		maxGroupSizeNightmare = 1
		canBurnInSunlight = false
		canBeWithered = false
		whitelist = ["#jungle", "#extreme_hills", "#underground", "#mesa", "#mountain", "#icy", "#savanna", "#beach", "#plains", "#swamp", "#forest", "#taiga", "#desert"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes"]

	["The Graveyard - Mob Spawning Config".skeleton_creeper]
		enabled = true
		#Range: 0 ~ 100
		weight = 20
		#Range: 1 ~ 100
		minGroupSizeSkeletonCreeper = 1
		#Range: 1 ~ 100
		maxGroupSizeSkeletonCreeper = 4
		canBurnInSunlight = true
		canBeWithered = false
		whitelist = ["#jungle", "#extreme_hills", "#underground", "#mesa", "#mountain", "#icy", "#savanna", "#beach", "#plains", "#swamp", "#forest", "#taiga", "#desert"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes"]

	["The Graveyard - Mob Spawning Config".acolyte]
		enabled = false
		#Range: 0 ~ 100
		weight = 0
		#Range: 1 ~ 100
		minGroupSizeAcolyte = 2
		#Range: 1 ~ 100
		maxGroupSizeAcolyte = 3
		canBurnInSunlight = false
		canBeWithered = false
		whitelist = ["#jungle", "#extreme_hills", "#underground", "#mesa", "#mountain", "#icy", "#savanna", "#beach", "#plains", "#swamp", "#forest", "#taiga", "#desert"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes"]

["The Graveyard - Horde Config"]

	["The Graveyard - Horde Config".horde]
		generate = true
		#Range: 0 ~ 1000
		size = 40
		#Range: 1 ~ 1000000
		ticksUntilSpawnHorde = 24000

["The Graveyard - Particle Config"]

	["The Graveyard - Particle Config".particle]
		generate = true
		#Range: 1 ~ 500
		frequency = 50

["The Graveyard - Additional Config"]

	["The Graveyard - Additional Config".urn]
		urnHasDoubleInventory = true

